# Generated by Django 4.0.1 on 2022-01-05 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
