# Generated by Django 4.0.1 on 2022-01-06 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_node_is_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='date',
            field=models.DateField(default='2022-01-04'),
        ),
    ]
