# Generated by Django 4.0.1 on 2022-01-06 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_alter_node_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
